### ISSUE TITLE
Wikidata

### ISSUE THREAD

**Issue by LOUGBERTI** [nadgeri14/KGPool#11]
Hello, in the process of replacing NYT dataset with wikidata, the code can run through, but the effect is very poor. Can you help me analyze the reason? You can release the code of wikidata version. Thank you very much.

**Comment by amiroft** [comment]
Hi,
I run the code on wikidata , how much is your f1 score?

**Comment by LOUGBERTI** [comment]
> Hi, I run the code on wikidata , how much is your f1 score?

86.44

**Comment by LOUGBERTI** [comment]
> Hi, I run the code on wikidata , how much is your f1 score?

Hello, you are useful P@K Has the index run over NYT? Do you have the code for this indicator?

**Comment by nadgeri14** [comment]
I have used the standard setting used in baseline papers. 
You can refer to [HRERE](https://github.com/billy-inn/HRERE) repo for the details

**Comment by LOUGBERTI** [comment]
> Hi, I run the code on wikidata , how much is your f1 score?
Hello, what is the result of your kgpool on Wiki

**Comment by nadgeri14** [comment]
> 

Hi you can find the details in the paper [here](https://aclanthology.org/2021.findings-acl.48.pdf)
