### ISSUE TITLE
Building the model befor defining variables

### ISSUE THREAD

**Issue by amiroft** [nadgeri14/KGPool#7]
Hi

following our discussion on :
https://github.com/nadgeri14/KGPool/issues/6

actually I had seen them:
from line 195 through 198 in train.py you have defined some variable meanwhile,
in line 173 when you build the GPGNN model:

 `
   ```
if (torch.cuda.is_available()):
        model = get_model(model_name)(model_params, embeddings, max_sent_len, n_out, kgpool_args, char2idx).cuda()
    else:
        model = get_model(model_name)(model_params, embeddings, max_sent_len, n_out, kgpool_args, char2idx)
```
`
  in module named our_model.py as you are trying to build model you need those variable(I mean sentence_input,.....)
where you defined them later...so when anybody wants to run you code will face error at line 173 which is namerror that there is no variable named ""sentence_input"" so on and so forth...
I think you define those variable in training loop but we also need them for building the model.
I appreciate your complete definition about it.

**Comment by nadgeri14** [comment]
Hi
For building the GPGNN model in our_model.py, if we look at the class definition (from line 21 to 78), then while creating the class, I have not used the variable sentence_input. 
But in for forward function of the class from line 81, I have used the variable sentence_input. 

Now, if we go the train.py file, then from lines 172 to 176, it's defining the class, as seen from above, we will not require the variable sentence_input. But, in the forward function of the model (211 to 220), we need the variable sentence_input which is passed to the function as variable sentence_input. 

Hope it helps 
Best 
Abhishek

**Comment by amiroft** [comment]
There was some problem with the data ,I could fix it and make the model train.
thank you and good job
