### ISSUE TITLE
test

### ISSUE THREAD

**Issue by amiroft** [nadgeri14/KGPool#8]
Hi,
when we want to run test.py we need model
in line 49 of test.py 
    load_model = "model-80.out" # you should choose the proper model to load
what is model-80.out ?
where did you save it?
 actually there is some problem with line 153
where:
model.load_state_dict(torch.load(load_model))
Thanks

**Comment by nadgeri14** [comment]
Hi, 
Yes, sorry the command to save the model is missing in the current train.py 

I have updated the code to save the model [here](https://github.com/nadgeri14/KGPool/blob/master/Context-Aggregator/train.py#L252)
You can find the saved model at save_folder.

**Comment by amiroft** [comment]
Thanks
