### ISSUE TITLE
how to train the model on wiki data

### ISSUE THREAD

**Issue by amiroft** [nadgeri14/KGPool#9]
Hi, 
I had train the kgpool model on NYT/freebase dataset, when tried your code on wiki data with source you provided [here](https://drive.google.com/file/d/1mmKLh6a78GVNizBoCGhs5ZMYJX2g-DIU/view)
the data structure is RDF format i.e (e1,rel,e2) but as you know for training KGPool we need sentence in which e1 and e2 exist . what is your advice ?

**Comment by nadgeri14** [comment]
Hi, 
If you look at the files in the folder enwiki-20160501 which contains the entire (unmodified) dataset, then if we look at the sample here. It is structured as : 
```{
	"vertexSet": [{
		"kbID": "Q430469",
		"type": "LEXICAL",
		"variable": false,
		"unique": false,
		"namedEntity": true,
		"tokenpositions": [0],
		"numericalValue": 0.0,
		"lexicalInput": "Tulostoma"
	}, {
		"kbID": "Q34740",
		"type": "LEXICAL",
		"variable": false,
		"unique": false,
		"namedEntity": true,
		"tokenpositions": [3],
		"numericalValue": 0.0,
		"lexicalInput": "genus"
	}, {
		"kbID": "Q913614",
		"type": "LEXICAL",
		"variable": false,
		"unique": false,
		"namedEntity": true,
		"tokenpositions": [13],
		"numericalValue": 0.0,
		"lexicalInput": "Agaricaceae"
	}],
	"edgeSet": [{
		"kbID": "P0",
		"right": [13],
		"left": [3]
	}],
	"tokens": ["Tulostoma", "is", "a", "genus", "of", "over", "100", "species", "of", "fungi", "in", "the", "family", "Agaricaceae", "."]
}

here tokens is the target sentence, and (e1 e2) are in vertex set.

**Comment by amiroft** [comment]
Thanks for the response

but there is a problem in above mentioned structure where in edgeSet kbID P0 or Pxxx has been used for addressing relation between two entities  which has no meaning in contrast to fb/NYT relations ...
is there any dictionary which maps the relations to meaningful relations for example : location/location/contains
?

**Comment by nadgeri14** [comment]
Yes, the mapping exists. 
It is a relation that exists in wikidata for example: https://www.wikidata.org/wiki/Property:P460
You can find the complete details of the dataset from the original paper: https://aclanthology.org/D17-1188.pdf

**Comment by amiroft** [comment]
Thanks for response
which structure should be fed into the model?

should
	`	"vertexSet": [{
		"kbID": "Q430469",
		"type": "LEXICAL",
		"variable": false,
		"unique": false,
		"namedEntity": true,
		"tokenpositions": [0],
		"numericalValue": 0.0,
		"lexicalInput": "Tulostoma"
	}, {
		"kbID": "Q34740",
		"type": "LEXICAL",
		"variable": false,
		"unique": false,
		"namedEntity": true,
		"tokenpositions": [3],
		"numericalValue": 0.0,
		"lexicalInput": "genus"
	}, {
		"kbID": "Q913614",
		"type": "LEXICAL",
		"variable": false,
		"unique": false,
		"namedEntity": true,
		"tokenpositions": [13],
		"numericalValue": 0.0,
		"lexicalInput": "Agaricaceae"
	}],
	"edgeSet": [{
		"kbID": "P0",
		"right": [13],
		"left": [3]
	}],
	"tokens": ["Tulostoma", "is", "a", "genus", "of", "over", "100", "species", "of", "fungi", "in", "the", "family", "Agaricaceae", "."]
}
`
 be modified so that it looks like NYT-Freebase dataset?

**Comment by LOUGBERTI** [comment]
> 感谢您的回复 ，应该将哪个结构输入模型？
> 
> 应该 ` "vertexSet": [{ "kbID": "Q430469", "type": "LEXICAL", "variable": false, "unique": false, "namedEntity": true, "tokenpositions": [0], "numericalValue": 0.0, "lexicalInput": "Tulostoma" }, { "kbID": "Q34740", "type": "LEXICAL", "variable": false, "unique": false, "namedEntity": true, "tokenpositions": [3], "numericalValue": 0.0, "lexicalInput": "genus" }, { "kbID": "Q913614", "type": "LEXICAL", "variable": false, "unique": false, "namedEntity": true, "tokenpositions": [13], "numericalValue": 0.0, "lexicalInput": "Agaricaceae" }], "edgeSet": [{ "kbID": "P0", "right": [13], "left": [3] }], "tokens": ["Tulostoma", "is", "a", "genus", "of", "over", "100", "species", "of", "fungi", "in", "the", "family", "Agaricaceae", "."] } ` 修改使它看起来像 NYT-Freebase 数据集？

Hello, have you solved this problem? I also try to run with Wiki, but there are some problems with the data

**Comment by amiroft** [comment]
Hi
yes I did.
feel free to ask your clear question about the data

**Comment by LOUGBERTI** [comment]
> 嗨 ，是的，我做到了。 随时询问有关数据的明确问题

Hello, what is the F1 effect of your running in wikidata

**Comment by LOUGBERTI** [comment]
> 嗨 ，是的，我做到了。 随时询问有关数据的明确问题

Hello, how much F1 have you achieved by running kgpool with wikidata
